// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvkzzkbwjntazemosbot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2a3p6a2J3am50YXplbW9zYm90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MjA3NzAsImV4cCI6MjA2MzM5Njc3MH0.fdlhAHGzYtW_z_j4sgD5V5-viOnbeGlhe5kD0NO8zq8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
