// This file is automatically generated. Do not edit it directly.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      brag_documents: {
        Row: {
          id: number
          user_name: string
          achievement: string
          description: string
          points: number
          created_at: string
        }
        Insert: {
          id?: number
          user_name: string
          achievement: string
          description: string
          points: number
          created_at?: string
        }
        Update: {
          id?: number
          user_name?: string
          achievement?: string
          description?: string
          points?: number
          created_at?: string
        }
      }
      attendance: {
        Row: {
          id: number
          user_name: string
          days_present: number
          total_days: number
          attendance_percentage: number
          last_updated: string
        }
        Insert: {
          id?: number
          user_name: string
          days_present: number
          total_days: number
          attendance_percentage: number
          last_updated?: string
        }
        Update: {
          id?: number
          user_name?: string
          days_present?: number
          total_days?: number
          attendance_percentage?: number
          last_updated?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      get_attendance_sbu_leaderboard: {
        Args: {
          p_start_date: string
          p_end_date: string
        }
        Returns: {
          sbu_id: string
          sbu_name: string
          rank: number
          total_employees: number
          avg_worked_hours: number
          missing_logs_percentage: number | null
          low_hours_percentage: number | null
          high_hours_percentage: number | null
          invalid_hours_percentage: number | null
          health_score: number | null
          employees_with_issues: number
        }[]
      }
      get_brag_document_sbu_completeness: {
        Args: {
          p_year: number
          p_month: number
          p_sbu_id?: string | null
        }
        Returns: {
          sbu_id: string
          sbu_name: string
          total_active_employees: number
          submitted_employees: number
          not_submitted_employees: number
          completion_percentage: number
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
  }
}
